# Generated by Django 5.1.4 on 2025-03-12 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_roomdesigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdesigns',
            name='room_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
