# Generated by Django 5.1.4 on 2025-03-12 14:11

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_roomdesigns_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdesigns',
            name='room_id',
            field=models.CharField(default=myapp.models.generate_unique_room_id, max_length=10, unique=True),
        ),
    ]
