# Generated by Django 5.1.4 on 2025-03-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_roomdesigns_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdesigns',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdesigns',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdesigns',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdesigns',
            name='floor_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomdesigns',
            name='height',
            field=models.FloatField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='roomdesigns',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdesigns',
            name='wall_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20, null=True),
        ),
    ]
