# Generated by Django 5.1.4 on 2025-03-14 13:32

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_roomdesigns_description_alter_roomdesigns_breadth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdesigns',
            name='room_id',
            field=models.CharField(default=myapp.models.generate_unique_room_id, max_length=8, unique=True),
        ),
    ]
