# Generated by Django 5.1.4 on 2025-03-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_roomdesigns_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdesigns',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
