# Generated by Django 5.1.4 on 2025-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_adminpanel_publicpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('request_model', 'Request Model')], default='contact', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
